# Generated by Django 3.1.6 on 2021-02-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210222_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', unique=True),
        ),
    ]
