# Generated by Django 3.1.6 on 2021-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210222_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
